### PR TITLE
Update error message regex

### PR DESCRIPTION
**Pull request by br4sco**
This PR updates the error message regex to reflect changes in Miking. In particular after https://github.com/miking-lang/miking/pull/687 is merged.

### CODE REVIEW

**Comment by EliasC** [comment]
Looks good! Do you mind pinging me when https://github.com/miking-lang/miking/pull/687 is merged?

**Comment by br4sco** [comment]
> Looks good! Do you mind pinging me when [miking-lang/miking#687](https://github.com/miking-lang/miking/pull/687) is merged?

Sure!

**Comment by br4sco** [comment]
The time has come. I made some tweaks to the regex in case you missed that.

**Comment by EliasC** [comment]
I saw the changes, and I saw that they were good =)

**Pull request merged**
